# INSTALL
steps:

# STEPS removed: will be done directly in App Engine
# - name: node:12
#   entrypoint: yarn
#   args: ['install']
# - name: node:12
#   entrypoint: yarn
#   args: ['run', 'build-react']
# - name: node:12
#   entrypoint: yarn
#   args: ['run', 'build-node']

# DEPLOY to App Engine - Default service
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']


# GLOBAL OPTIONS
options:
  env: ['NODE_ENV=production']
  logStreamingOption: STREAM_ON
  logging: LEGACY

