# INSTALL
steps:
- name: node:12
  entrypoint: yarn
  args: ['install']
- name: node:12
  entrypoint: yarn
  args: ['run', 'build-react']
- name: node:12
  entrypoint: yarn
  args: ['run', 'build-node']


# DEPLOY to App Engine - Temp service
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'temp.yaml']
  dir: 'dist' # /workspace/<dir>


# GLOBAL OPTIONS
options:
  env: ['NODE_ENV=production']
  logStreamingOption: STREAM_ON
  logging: LEGACY

