# INSTALL
steps:
- name: node:12
  entrypoint: yarn
  args: ['install']
- name: node
  entrypoint: yarn
  args: ['add', 'webpack-cli']
- name: node
  entrypoint: yarn
  args: ['run', 'build-react']
- name: node
  entrypoint: yarn
  args: ['run', 'build-node']

# DEPLOY to App Engine
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'
